#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

# shellcheck disable=SC2086
exec s6-setuidgid hotio "${APP_DIR}/jackett" --NoRestart --ListenPublic --NoUpdates --DataFolder="${CONFIG_DIR}/app" ${ARGS}
