#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

exec s6-setuidgid hotio mono --debug "${APP_DIR}/JackettConsole.exe" --NoRestart --ListenPublic --NoUpdates --DataFolder="${CONFIG_DIR}/app"
